export const queryKeys = {
  items: {
    all: ['items'] as const,
    lists: () => [...queryKeys.items.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.items.lists(), filters] as const,
    details: () => [...queryKeys.items.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.items.details(), id] as const,
    byCode: (code: string) => [...queryKeys.items.all, 'code', code] as const,
    stats: () => [...queryKeys.items.all, 'stats'] as const,
    intake: () => [...queryKeys.items.all, 'intake'] as const,
    media: (id: string) => [...queryKeys.items.all, 'media', id] as const,
    costs: (id: string) => [...queryKeys.items.all, 'costs', id] as const,
    auditLogs: (id: string) => [...queryKeys.items.all, 'audit-logs', id] as const,
  },
  productModels: {
    all: ['product-models'] as const,
    lists: () => [...queryKeys.productModels.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.productModels.lists(), filters] as const,
    details: () => [...queryKeys.productModels.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.productModels.details(), id] as const,
    media: (id: string) => [...queryKeys.productModels.all, 'media', id] as const,
  },
  suppliers: {
    all: ['suppliers'] as const,
    lists: () => [...queryKeys.suppliers.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.suppliers.lists(), filters] as const,
    details: () => [...queryKeys.suppliers.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.suppliers.details(), id] as const,
  },
  sellGroups: {
    all: ['sell-groups'] as const,
    lists: () => [...queryKeys.sellGroups.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.sellGroups.lists(), filters] as const,
    details: () => [...queryKeys.sellGroups.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.sellGroups.details(), id] as const,
    items: (id: string) => [...queryKeys.sellGroups.all, 'items', id] as const,
    available: (id: string) => [...queryKeys.sellGroups.all, 'available', id] as const,
  },
  orders: {
    all: ['orders'] as const,
    lists: () => [...queryKeys.orders.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.orders.lists(), filters] as const,
    details: () => [...queryKeys.orders.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.orders.details(), id] as const,
  },
  customers: {
    all: ['customers'] as const,
    lists: () => [...queryKeys.customers.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.customers.lists(), filters] as const,
    details: () => [...queryKeys.customers.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.customers.details(), id] as const,
  },
  customerAddresses: {
    all: ['customer-addresses'] as const,
    lists: () => [...queryKeys.customerAddresses.all, 'list'] as const,
    list: (customerId: string) => [...queryKeys.customerAddresses.lists(), customerId] as const,
  },
  shop: {
    all: ['shop'] as const,
    products: (filters: Record<string, unknown>) => [...queryKeys.shop.all, 'products', filters] as const,
    productDetail: (productModelId: string) => [...queryKeys.shop.all, 'detail', productModelId] as const,
    sellGroupByCode: (code: string) => [...queryKeys.shop.all, 'code', code] as const,
    brands: () => [...queryKeys.shop.all, 'brands'] as const,
  },
  kaitori: {
    all: ['kaitori'] as const,
    lists: () => [...queryKeys.kaitori.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.kaitori.lists(), filters] as const,
    details: () => [...queryKeys.kaitori.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.kaitori.details(), id] as const,
    byCode: (code: string) => [...queryKeys.kaitori.all, 'code', code] as const,
    priceList: () => [...queryKeys.kaitori.all, 'price-list'] as const,
  },
  dashboard: {
    all: ['dashboard'] as const,
    stats: () => [...queryKeys.dashboard.all, 'stats'] as const,
  },
  intakeReceipts: {
    all: ['intake-receipts'] as const,
    lists: () => [...queryKeys.intakeReceipts.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.intakeReceipts.lists(), filters] as const,
    details: () => [...queryKeys.intakeReceipts.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.intakeReceipts.details(), id] as const,
    adjustments: (receiptId: string) => [...queryKeys.intakeReceipts.all, 'adjustments', receiptId] as const,
    items: (receiptId: string) => [...queryKeys.intakeReceipts.all, 'items', receiptId] as const,
  },
  categories: {
    all: ['categories'] as const,
    list: () => [...queryKeys.categories.all, 'list'] as const,
    details: () => [...queryKeys.categories.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.categories.details(), id] as const,
  },
  aiConfigurations: {
    all: ['ai-configurations'] as const,
    lists: () => [...queryKeys.aiConfigurations.all, 'list'] as const,
    list: () => [...queryKeys.aiConfigurations.lists()] as const,
    active: () => [...queryKeys.aiConfigurations.all, 'active'] as const,
  },
  aiPrompts: {
    all: ['ai-prompts'] as const,
    lists: () => [...queryKeys.aiPrompts.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.aiPrompts.lists(), filters] as const,
    active: (mediaType?: string) => [...queryKeys.aiPrompts.all, 'active', mediaType] as const,
  },
  offers: {
    all: ['offers'] as const,
    lists: () => [...queryKeys.offers.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.offers.lists(), filters] as const,
    details: () => [...queryKeys.offers.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.offers.details(), id] as const,
    byCode: (code: string) => [...queryKeys.offers.all, 'code', code] as const,
    forItem: (itemId: string) => [...queryKeys.offers.all, 'item', itemId] as const,
  },
  returns: {
    all: ['returns'] as const,
    lists: () => [...queryKeys.returns.all, 'list'] as const,
    list: (filters: Record<string, unknown>) => [...queryKeys.returns.lists(), filters] as const,
    details: () => [...queryKeys.returns.all, 'detail'] as const,
    detail: (id: string) => [...queryKeys.returns.details(), id] as const,
    customer: (customerId: string) => [...queryKeys.returns.all, 'customer', customerId] as const,
    media: (id: string) => [...queryKeys.returns.all, 'media', id] as const,
  },
  postalCodes: {
    all: ['postal-codes'] as const,
    lookup: (code: string) => ['postal-codes', 'lookup', code] as const,
    reverse: (prefectureJa: string, cityJa: string, townJa: string) =>
      ['postal-codes', 'reverse', prefectureJa, cityJa, townJa] as const,
  },
}
